import mongoose from "mongoose";
import dotenv from "dotenv";
import User from "./model/user.model.js";
import Product from "./model/products.model.js";

import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../.env") });

const mongoUri = process.env.MONGO;

const seedData = async () => {
  try {
    console.log("Connecting to MongoDB...");
    await mongoose.connect(mongoUri);
    console.log("Connected to MongoDB successfully!");

    // Get or create a seller user to associate products with
    let seller = await User.findOne({ role: "seller" });
    if (!seller) {
      seller = await User.findOne();
    }
    if (!seller) {
      console.log("No user found. Creating a dummy seller...");
      seller = new User({
        username: "StoreAdmin",
        email: "admin@shopcart.com",
        password: "hashedpassword123", // dummy password
        role: "seller",
      });
      await seller.save();
    }

    console.log(`Using seller user: ${seller.username} (${seller._id})`);

    // Clear existing products
    await Product.deleteMany({});
    console.log("Cleared existing products from database.");

    // High quality seeded products with realistic PKR prices
    const products = [
      {
        name: "HP Pavilion Laptop 15",
        description: "15.6-inch FHD Display, Intel Core i5 12th Gen, 8GB RAM, 512GB SSD. Perfect for daily tasks and productivity.",
        category: "Electronics",
        tags: ["laptop", "laptap", "hp", "pavilion", "electronics"],
        originalPrice: 185000,
        discountPrice: 165000,
        stock: 12,
        images: ["https://example.com/hp-pavilion.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.5,
      },
      {
        name: "Dell Inspiron 15 Laptop",
        description: "Intel Core i7 11th Gen, 16GB DDR4 RAM, 512GB NVMe SSD, Intel Iris Xe Graphics. Premium build quality.",
        category: "Electronics",
        tags: ["laptop", "laptap", "dell", "inspiron", "electronics"],
        originalPrice: 195000,
        discountPrice: 175000,
        stock: 8,
        images: ["https://example.com/dell-inspiron.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: false,
        ratings: 4.2,
      },
      {
        name: "Apple MacBook Air M2",
        description: "Apple M2 chip, 13.6-inch Liquid Retina Display, 8GB Unified Memory, 256GB SSD storage. Exceptionally thin and fast.",
        category: "Electronics",
        tags: ["laptop", "laptap", "apple", "macbook", "electronics"],
        originalPrice: 380000,
        discountPrice: 345000,
        stock: 5,
        images: ["https://example.com/macbook-air.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: false,
        featuredProducts: true,
        ratings: 4.8,
      },
      {
        name: "Lenovo IdeaPad Slim 3",
        description: "AMD Ryzen 5, 8GB RAM, 512GB SSD, Windows 11 Home. Sleek design and long battery life.",
        category: "Electronics",
        tags: ["laptop", "laptap", "lenovo", "ideapad", "electronics"],
        originalPrice: 140000,
        discountPrice: 125000,
        stock: 15,
        images: ["https://example.com/lenovo-ideapad.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.0,
      },
      {
        name: "Organic Matte Lipstick",
        description: "Cruelty-free, organic velvet matte lipstick. Richly pigmented and long-lasting formulation.",
        category: "Beauty",
        tags: ["cosmetic", "lipstick", "organic", "beauty"],
        originalPrice: 2500,
        discountPrice: 1800,
        stock: 50,
        images: ["https://example.com/lipstick.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.6,
      },
      {
        name: "Hydrating Skin Foundation",
        description: "Liquid foundation with medium buildable coverage and a naturally radiant finish. Contains hyaluronic acid.",
        category: "Beauty",
        tags: ["cosmetic", "foundation", "skin", "beauty"],
        originalPrice: 4500,
        discountPrice: 3800,
        stock: 30,
        images: ["https://example.com/foundation.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: false,
        ratings: 4.3,
      },
      {
        name: "Natural Eyeshadow Palette",
        description: "12 warm neutrals and sparkling shimmers. Highly blendable powder formula with a velvety texture.",
        category: "Beauty",
        tags: ["cosmetic", "eyeshadow", "palette", "beauty"],
        originalPrice: 6000,
        discountPrice: 4999,
        stock: 25,
        images: ["https://example.com/eyeshadow.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: false,
        featuredProducts: true,
        ratings: 4.7,
      },
      {
        name: "Glow Moisturizing Cream",
        description: "Daily face moisturizer with Vitamin C and Shea Butter. Instantly locks in moisture for a youthful glow.",
        category: "Beauty",
        tags: ["cosmetic", "moisturizer", "glow", "beauty"],
        originalPrice: 3200,
        discountPrice: 2600,
        stock: 40,
        images: ["https://example.com/moisturizer.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.4,
      },
      {
        name: "Ergonomic Lounge Chair",
        description: "Solid oak wood frame with premium linen fabric. Ergonomic curved seat design for maximum comfort.",
        category: "Furniture",
        tags: ["furniture", "chair", "ergonomic", "lounge"],
        originalPrice: 25000,
        discountPrice: 19500,
        stock: 6,
        images: ["https://example.com/chair.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.5,
      },
      {
        name: "Minimalist Wooden Desk",
        description: "Spacious wooden table top with steel frame support. Clean, modern writing desk for home office.",
        category: "Furniture",
        tags: ["furniture", "table", "desk", "wooden"],
        originalPrice: 35000,
        discountPrice: 28000,
        stock: 10,
        images: ["https://example.com/desk.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: false,
        featuredProducts: true,
        ratings: 4.6,
      },
      {
        name: "Luxury 3-Seater Sofa",
        description: "Plush velvet upholstery, pocket spring cushions, and solid wood legs. Complete your modern living room.",
        category: "Furniture",
        tags: ["furniture", "sofa", "luxury"],
        originalPrice: 120000,
        discountPrice: 95000,
        stock: 4,
        images: ["https://example.com/sofa.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: false,
        ratings: 4.7,
      },
      {
        name: "The Psychology of Money",
        description: "Timeless lessons on wealth, greed, and happiness by Morgan Housel. Essential reading for personal finance.",
        category: "Books",
        tags: ["book", "money", "psychology"],
        originalPrice: 1800,
        discountPrice: 1200,
        stock: 100,
        images: ["https://example.com/book-psychology.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.9,
      },
      {
        name: "Atomic Habits",
        description: "An easy & proven way to build good habits & break bad ones by James Clear. Global bestseller.",
        category: "Books",
        tags: ["book", "habits", "self-help"],
        originalPrice: 1500,
        discountPrice: 999,
        stock: 120,
        images: ["https://example.com/book-habits.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: false,
        featuredProducts: true,
        ratings: 4.9,
      },
      {
        name: "Head & Shoulders Classic Clean Shampoo",
        description: "Deeply cleans hair while targeting the root cause of dandruff for flake-free, beautiful hair.",
        category: "Beauty",
        tags: ["shampoo", "headandshoulders", "head & shoulders", "personal care", "beauty"],
        originalPrice: 950,
        discountPrice: 820,
        stock: 60,
        images: ["https://example.com/shampoo.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.5,
      },
      {
        name: "Multi-Surface Premium Floor Cleaner",
        description: "Tough on grease and grime, leaving floors sparkling clean with a fresh lemon scent.",
        category: "Household",
        tags: ["cleaner", "floor cleaner", "household"],
        originalPrice: 1200,
        discountPrice: 980,
        stock: 45,
        images: ["https://example.com/cleaner.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.2,
      },
      {
        name: "Ultra Wash Concentrated Liquid Laundry Detergent",
        description: "Advanced stain-lifting formula that keeps clothes bright and smelling fresh wash after wash.",
        category: "Household",
        tags: ["detergent", "laundry", "wash", "household"],
        originalPrice: 1600,
        discountPrice: 1350,
        stock: 35,
        images: ["https://example.com/detergent.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: false,
        ratings: 4.4,
      },
      {
        name: "Vendify Over-Ear Wireless Headphones",
        description: "Active noise cancellation, 40 hours of battery life, and crystal-clear audio quality.",
        category: "Electronics",
        tags: ["headphones", "headphone", "audio", "electronics"],
        originalPrice: 12500,
        discountPrice: 9999,
        stock: 20,
        images: ["https://example.com/headphones.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.6,
      },
      {
        name: "Vendify Next-Gen PlayConsole Pro",
        description: "Experience ultra-high speed SSD loading, 4K gaming, and deep immersive gameplay console features.",
        category: "Electronics",
        tags: ["playconsole", "console", "gaming console", "electronics"],
        originalPrice: 165000,
        discountPrice: 145000,
        stock: 6,
        images: ["https://example.com/console.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: false,
        featuredProducts: true,
        ratings: 4.7,
      },
      {
        name: "Heavy Duty Kitchen Cleaning Sponge (Spanch)",
        description: "Super absorbent scrubbing sponge, ideal for tough kitchen cleaning and dishes.",
        category: "Household",
        tags: ["sponge", "spanch", "cleaning", "household"],
        originalPrice: 450,
        discountPrice: 350,
        stock: 150,
        images: ["https://example.com/sponge.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: false,
        ratings: 4.3,
      },
      {
        name: "Digital Instant Read Thermometer (Thermameter)",
        description: "Quick and accurate digital thermometer suitable for medical, family, and home use.",
        category: "Electronics",
        tags: ["thermometer", "thermameter", "digital thermometer", "electronics", "health"],
        originalPrice: 2800,
        discountPrice: 1950,
        stock: 40,
        images: ["https://example.com/thermometer.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.4,
      },
      {
        name: "Complete Care Toothbrush and Toothpaste Set",
        description: "Soft-bristle advanced toothbrush paired with fluoride toothpaste for complete oral protection.",
        category: "Beauty",
        tags: ["toothbrush", "toothpaste", "toothandbrush", "oral care", "beauty"],
        originalPrice: 850,
        discountPrice: 650,
        stock: 120,
        images: ["https://example.com/toothbrush.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.5,
      },
      {
        name: "Premium Vitamin C Supplements (500mg)",
        description: "Boosts immune system, promotes skin health, and supports natural antioxidant defense.",
        category: "Beauty",
        tags: ["vitamin c", "vitaminc", "vitamin", "supplement", "beauty", "health"],
        originalPrice: 3200,
        discountPrice: 2400,
        stock: 80,
        images: ["https://example.com/vitaminc.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: false,
        featuredProducts: true,
        ratings: 4.8,
      },
      {
        name: "Vendify Sterile Comfort Bandaches (Bandages)",
        description: "Flexible fabric adhesive bandages for first-aid protection of minor cuts and scrapes.",
        category: "Beauty",
        tags: ["bandage", "bandache", "band-aid", "bandaid", "aid", "beauty", "health"],
        originalPrice: 600,
        discountPrice: 450,
        stock: 200,
        images: ["https://example.com/bandages.jpg"],
        shop: `${seller.username}'s Store`,
        shopId: seller._id.toString(),
        userRef: seller._id,
        bestDeals: true,
        featuredProducts: true,
        ratings: 4.7,
      }
    ];

    await Product.insertMany(products);
    console.log("Seeded database with PKR products successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

seedData();
